const plugin = require("tailwindcss/plugin");
const containerQueries = require("@tailwindcss/container-queries");
const theme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./app/javascript/src/**/*.{js,jsx,ts,tsx}",
    "./stories/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    "text-xxs",
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
  ],
  theme: {
    colors: {
      // MINT Color Kit scales
      white: "#FFFFFF",
      black: "#000000",
      alpha: {
        black: {
          50: "rgba(0, 0, 0, 0.05);",
          100: "rgba(0, 0, 0, 0.12);",
          200: "rgba(0, 0, 0, 0.20);",
          300: "rgba(0, 0, 0, 0.30);",
          400: "rgba(0, 0, 0, 0.42);",
          500: "rgba(0, 0, 0, 0.52);",
          600: "rgba(0, 0, 0, 0.63);",
          700: "rgba(0, 0, 0, 0.71);",
          800: "rgba(0, 0, 0, 0.80);",
          900: "rgba(0, 0, 0, 0.87);",
        },
        white: {
          50: "rgba(255, 255, 255, 0.05);",
          100: "rgba(255, 255, 255, 0.12);",
          200: "rgba(255, 255, 255, 0.20);",
          300: "rgba(255, 255, 255, 0.30);",
          400: "rgba(255, 255, 255, 0.42);",
          500: "rgba(255, 255, 255, 0.52);",
          600: "rgba(255, 255, 255, 0.63);",
          700: "rgba(255, 255, 255, 0.71);",
          800: "rgba(255, 255, 255, 0.80);",
          900: "rgba(255, 255, 255, 0.87);",
        },
      },
      gray: {
        25: "#F7F7F6",
        50: "#F2F1ED",
        100: "#DEDDD7",
        200: "#C5C4BF",
        300: "#AAA9A4",
        400: "#8A8985",
        500: "#727272",
        600: "#575757",
        700: "#444444",
        800: "#303030",
        900: "#222222",
        1000: "#151515",
        "50a": "#F6F6F2",
        "100a": "#E7E3D5",
        "200a": "#CDC9BA",
      },
      green: {
        25: "#F0F8F5",
        50: "#E4F3EC",
        100: "#BEE6D5",
        200: "#9CD2BB",
        300: "#71B69A",
        400: "#409D7C",
        500: "#008060",
        600: "#006452",
        700: "#00473C",
        800: "#133A33",
        900: "#0A2621",
        "200a": "#00DDA9",
      },
      yellow: {
        25: "#FFF5EA",
        50: "#FFEBD5",
        100: "#FFD6A2",
        200: "#F5C073",
        300: "#E8A442",
        400: "#C6833F",
        500: "#976740",
        600: "#724F3B",
        700: "#583E32",
        800: "#3F2E28",
        900: "#291D18",
        "200a": "#FFBC2F",
      },
      orange: {
        25: "#FFF4F1",
        50: "#FFEDE7",
        100: "#FFD5C7",
        200: "#FFB49D",
        300: "#F78E72",
        400: "#E06B4F",
        500: "#BF4E36",
        600: "#903E28",
        700: "#713022",
        800: "#512115",
        900: "#3B170D",
        "300a": "#FF7B40",
      },
      red: {
        25: "#FFF4F6",
        50: "#FFE8EC",
        100: "#FFCED3",
        200: "#FFAEB8",
        300: "#FC8492",
        400: "#E25263",
        500: "#C73D4F",
        600: "#9F2946",
        700: "#7C1B3D",
        800: "#5F0F2E",
        900: "#441024",
        "500a": "#DF003B",
      },
      violet: {
        25: "#FCF4FA",
        50: "#FAECF6",
        100: "#EBD7E5",
        200: "#D7BECF",
        300: "#C59FB7",
        400: "#AB7E9B",
        500: "#88637B",
        600: "#6D4C61",
        700: "#5D3D52",
        800: "#40293A",
        900: "#2D1D27",
        "200a": "#E29EFF",
      },
      purple: {
        25: "#F6F6FF",
        50: "#F0EFFF",
        100: "#D8D7F8",
        200: "#C4C1F4",
        300: "#A4A1EA",
        400: "#8C7EE2",
        500: "#7061C2",
        600: "#574E92",
        700: "#423B72",
        800: "#302B55",
        900: "#211D3D",
        "300a": "#AA98FF",
      },
      ai: {
        purple: "#5264FF",
        pink: "#FF88FF",
        orange: "#FF9966",
      },
      blue: {
        25: "#F2F7FF",
        50: "#EAF1FF",
        100: "#CCDEFF",
        200: "#A7C8FF",
        300: "#76ABF5",
        400: "#498DE0",
        500: "#386FB1",
        600: "#2C588F",
        700: "#204571",
        800: "#153152",
        900: "#0F2239",
        "300a": "#51B9FF",
      },
      cyan: {
        25: "#F0F8FA",
        50: "#E6F3F7",
        100: "#C4E2ED",
        200: "#9ACFE1",
        300: "#6BB3C7",
        400: "#2F98AE",
        500: "#00788C",
        600: "#006070",
        700: "#004753",
        800: "#0C3842",
        900: "#07272F",
        "200a": "#36D6FF",
      },
      mist: {
        25: "#F1F8F8",
        50: "#EAF4F4",
        100: "#CFE0E0",
        200: "#B4CCCC",
        300: "#95AEAE",
        400: "#789191",
        500: "#5F7878",
        600: "#455D5D",
        700: "#304A4A",
        800: "#1E3636",
        900: "#182D2D",
        "200a": "#84D5D5",
      },
      cash: {
        25: "#F3F8F3",
        50: "#ECF3EB",
        100: "#D4E1D3",
        200: "#BECCBD",
        300: "#9DB09C",
        400: "#7F907E",
        500: "#667465",
        600: "#515C50",
        700: "#3D463C",
        800: "#2C322B",
        900: "#1D221C",
        "200a": "#AADD88",
      },

      // MINT Product tokens
      "background-default": "var(--background-default)",
      "background-light": "var(--background-light)",
      "background-dark": "var(--background-dark)",
      "button-background-default": "var(--button-background-default)",
      "button-background-default-hover":
        "var(--button-background-default-hover)",
      "button-background-default-pressed":
        "var(--button-background-default-pressed)",
      "button-background-primary": "var(--button-background-primary)",
      "button-background-primary-hover":
        "var(--button-background-primary-hover)",
      "button-background-primary-pressed":
        "var(--button-background-primary-pressed)",
      "button-background-disabled": "var(--button-background-disabled)",
      "surface-info": "var(--surface-info)",
      "surface-critical": "var(--surface-critical)",
      "surface-success": "var(--surface-success)",
      "border-default": "var(--border-default)",
      "border-muted": "var(--border-muted)",
      "border-strong": "var(--border-strong)",
      "text-default": "var(--text-default)",
      "text-hover": "var(--text-hover)",
      "text-muted": "var(--text-muted)",
      "text-disabled": "var(--text-disabled)",
      "text-critical": "var(--text-critical)",
      "text-success": "var(--text-success)",
      "text-info": "var(--text-info)",
      "text-on-primary": "var(--text-on-primary)",
      "text-on-critical": "var(--text-on-critical)",
      "icon-default": "var(--icon-default)",
      "icon-strong": "var(--icon-strong)",
      "icon-muted": "var(--icon-muted)",
      "icon-disabled": "var(--icon-disabled)",
      "icon-critical": "var(--icon-critical)",
      "icon-success": "var(--icon-success)",
      "icon-info": "var(--icon-info)",
      "icon-on-primary": "var(--icon-on-primary)",
      "icon-on-critical": "var(--icon-on-critical)",
      "action-primary": "var(--action-primary)",
      "action-primary-hover": "var(--action-primary-hover)",
      "action-primary-pressed": "var(--action-primary-pressed)",
      "action-primary-disabled": "var(--action-primary-disabled)",
      "action-critical": "var(--action-critical)",
      "action-critical-hover": "var(--action-critical-hover)",
      "action-critical-pressed": "var(--action-critical-pressed)",
      "action-critical-disabled": "var(--action-critical-disabled)",
      "action-default": "var(--action-default)",
      "action-default-hover": "var(--action-default-hover)",
      "action-default-pressed": "var(--action-default-pressed)",
      "action-default-disabled": "var(--action-default-disabled)",
      "checkbox-border": "var(--checkbox-border)",

      // Data Viz tokens
      qualitative: {
        positive: "#34A680",
        negative: "#BB0044",
        neutral: "#CDC9BA",
      },

      categorical: {
        1: "#007788",
        2: "#89C6C6",
        3: "#6D3C7C",
        4: "#7479E6",
        5: "#A22C70",
        6: "#F97F50",
        7: "#7E9983",
        8: "#F9BC4D",
      },

      // Misc classes
      current: "currentColor",
      inherit: "inherit",
      transparent: "transparent",
    },
    extend: {
      borderWidth: {
        3: "3px",
      },
      borderRadius: {
        md: "0.25rem",
      },
      spacing: {
        default: "16px",
        xxs: "2px",
        xs: "4px",
        s: "8px",
        m: "16px",
        l: "32px",
        xl: "64px",
      },
      minWidth: {
        "2xs": "16rem",
        "3xs": "12rem",
        "4xs": "8rem",
      },
      maxWidth: {
        "2xs": "16rem",
        "3xs": "12rem",
        "4xs": "8rem",
        "24/25": "96%",
        "9/25": "36%",
      },
      width: {
        192: "48rem",
      },
      minHeight: (theme) => ({
        ...theme("spacing"),
      }),
      fontSize: {
        "4xl": [
          "40px",
          { fontWeight: 500, letterSpacing: "-0.5px", lineHeight: "44px" },
        ],
        "3xl": [
          "36px",
          { fontWeight: 500, letterSpacing: "-0.5px", lineHeight: "42px" },
        ],
        "2xl": [
          "32px",
          { fontWeight: 500, letterSpacing: "-0.5px", lineHeight: "40px" },
        ],
        xl: ["24px", { fontWeight: 500, lineHeight: "32px" }],
        lg: ["20px", { fontWeight: 500, lineHeight: "32px" }],
        base: ["16px", "24px"],
        sm: ["14px", "20px"],
        xs: ["12px", "16px"],
        xxs: ["10px", { letterSpacing: "0.1px", lineHeight: "14px" }],
      },
      fontWeight: {
        normal: 400,
        medium: 500,
        bold: 700,
      },
      boxShadow: {
        selectBar: "0 1px 0px 0 rgba(0, 0, 0, 0.05)",
      },
      backgroundImage: {
        "ai-two-stop-gradient": "linear-gradient(to right, #5264FF, #FF88FF)",
        "ai-three-stop-gradient":
          "linear-gradient(to right, #5264FF, #FF88FF, #FF9966)",
        "ai-looping-gradient":
          "linear-gradient(to right, #5264FF, #FF88FF,  #FF9966, #FF88FF, #5264FF)",
        "ai-looping-gradient-with-border":
          "linear-gradient(white, white), linear-gradient(to right, #5264FF, #FF88FF,  #FF9966, #FF88FF, #5264FF)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0%" },
          "100%": { opacity: "100%" },
        },
        fadeInOut: {
          "0%, 100%": { opacity: "0%" },
          "50%": { opacity: "100%" },
        },
        backgroundPulse: {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
      },
      backgroundSize: {
        "300%": "300%",
      },
      animation: {
        fadeIn: "fadeIn 0.5s ease-in-out forwards",
        fadeInOut: "fadeIn 1.5s ease-in-out infinite",
        backgroundPulse: "backgroundPulse 4s ease-in-out infinite",
      },
    },

    /**
     * Are you sure you want to update the config below?
     *
     * Changes made below will overwrite the default tailwind config.
     * Any UI that depends on default tailwind classes will break.
     */
    screens: {
      //
      // temporarily adding tailwind defaults under mint- namespace to make migration from old custom breakpoints easier
      "mint-sm": theme.screens.sm,
      "mint-md": theme.screens.md,
      "mint-lg": theme.screens.lg,
      "mint-xl": theme.screens.xl,
      "mint-2xl": theme.screens["2xl"],
    },
    fontFamily: {
      mono: ["jetbrains-mono", ...theme.fontFamily.mono],
      sans: ["inter", ...theme.fontFamily.sans],
    },
    themes: (theme) => {
      const colors = theme("colors");

      // MINT web
      const themeLight = {
        "--background-default": colors.white,
        "--background-light": colors.gray[25],
        "--background-dark": colors.gray[800],
        "--button-background-default": colors.white,
        "--button-background-default-hover": colors.gray[25],
        "--button-background-default-pressed": colors.gray[50],
        "--button-background-primary": colors.blue[500],
        "--button-background-primary-hover": colors.blue[600],
        "--button-background-primary-pressed": colors.blue[700],
        "--button-background-disabled": colors.blue[25],
        "--surface-info": colors.yellow[25],
        "--surface-critical": colors.red[25],
        "--surface-success": colors.green[25],
        "--border-default": colors.gray[100],
        "--border-muted": colors.gray[50],
        "--border-strong": colors.gray[200],
        "--text-default": colors.gray[800],
        "--text-hover": colors.gray[500],
        "--text-muted": colors.gray[600],
        "--text-disabled": colors.gray[700],
        "--text-critical": colors.red[500],
        "--text-success": colors.green[500],
        "--text-info": colors.orange[500],
        "--text-on-primary": colors.white,
        "--text-on-critical": colors.white,
        "--icon-default": colors.gray[700],
        "--icon-strong": colors.gray[900],
        "--icon-muted": colors.gray[700],
        "--icon-disabled": colors.gray[500],
        "--icon-critical": colors.red[500],
        "--icon-success": colors.green[500],
        "--icon-info": colors.orange[500],
        "--icon-on-primary": colors.white,
        "--icon-on-critical": colors.white,
        "--action-primary": colors.green[500],
        "--action-primary-hover": colors.green[600],
        "--action-primary-pressed": colors.green[700],
        "--action-primary-disabled": colors.green[25],
        "--action-critical": colors.red[500],
        "--action-critical-hover": colors.red[600],
        "--action-critical-pressed": colors.red[700],
        "--action-critical-disabled": colors.red[25],
        "--action-default": colors.white,
        "--action-default-hover": colors.gray[50],
        "--action-default-pressed": colors.gray[100],
        "--action-default-disabled": colors.gray[25],
        "--checkbox-border": colors.black[900],
      };

      const themeDark = {
        "--background-default": colors.gray[900],
        "--background-light": colors.alpha.black[900],
        "--background-dark": colors.gray[900],
        "--button-background-default": colors.alpha.black[900],
        "--button-background-default-hover": colors.alpha.black[900],
        "--button-background-default-pressed": colors.alpha.black[900],
        "--button-background-primary": colors.alpha.black[900],
        "--button-background-primary-hover": colors.alpha.black[900],
        "--button-background-primary-pressed": colors.alpha.black[900],
        "--button-background-disabled": colors.alpha.black[900],
        "--surface-info": colors.alpha.black[900],
        "--surface-critical": colors.alpha.black[900],
        "--surface-success": colors.alpha.black[900],
        "--border-default": colors.alpha.black[900],
        "--border-muted": colors.alpha.black[900],
        "--border-strong": colors.alpha.black[900],
        "--text-default": colors.alpha.white[900],
        "--text-hover": colors.alpha.black[900],
        "--text-muted": colors.alpha.white[700],
        "--text-disabled": colors.alpha.black[900],
        "--text-critical": colors.alpha.black[900],
        "--text-success": colors.alpha.black[900],
        "--text-info": colors.orange[400],
        "--text-on-primary": colors.alpha.black[900],
        "--text-on-critical": colors.alpha.black[900],
        "--icon-default": colors.alpha.white[700],
        "--icon-strong": colors.alpha.white[900],
        "--icon-muted": colors.alpha.white[500],
        "--icon-disabled": colors.alpha.black[900],
        "--icon-critical": colors.alpha.black[900],
        "--icon-success": colors.alpha.black[900],
        "--icon-info": colors.alpha.black[900],
        "--icon-on-primary": colors.alpha.black[900],
        "--icon-on-critical": colors.alpha.black[900],
        "--action-primary": colors.alpha.black[900],
        "--action-primary-hover": colors.alpha.black[900],
        "--action-primary-pressed": colors.alpha.black[900],
        "--action-primary-disabled": colors.alpha.black[900],
        "--action-critical": colors.alpha.black[900],
        "--action-critical-hover": colors.alpha.black[900],
        "--action-critical-pressed": colors.alpha.black[900],
        "--action-critical-disabled": colors.alpha.black[900],
        "--action-default": colors.alpha.black[900],
        "--action-default-hover": colors.alpha.black[900],
        "--action-default-pressed": colors.alpha.black[900],
        "--action-default-disabled": colors.alpha.black[900],
        "--checkbox-border": colors.alpha.black[900],
      };

      return {
        ":root": themeLight,
        ".theme--light": themeLight,
        ".experimental__theme--dark": themeDark,
      };
    },
  },
  plugins: [
    containerQueries,
    plugin(({ addComponents, theme }) => {
      const themes = theme("themes");
      if (themes) {
        addComponents(themes);
      }
    }),
  ],
};

module.exports = config;
